apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80 #public traffic or other services will access the pod on this port
      targetPort: 8080 #port the pod/container will listen on
